"""
generate_pipe_mesh.py
---------------------
Generates a hollow cylinder STL mesh (binary format) for use as the
Gazebo pipe world model.

Geometry
--------
  Inner radius  : INNER_RADIUS  (0.15 m, matches pipe_radius default)
  Wall thickness: WALL_THICKNESS (0.03 m)
  Outer radius  : INNER_RADIUS + WALL_THICKNESS = 0.18 m
  Length        : PIPE_LENGTH (5.0 m, along the Z axis)

The mesh has four surfaces:
  1. Outer cylinder  (normals pointing outward)
  2. Inner cylinder  (normals pointing inward - what the robot camera sees)
  3. End cap at Z=0  (annular ring, normals pointing -Z)
  4. End cap at Z=L  (annular ring, normals pointing +Z)

Dependencies: numpy only (no trimesh / open3d required).

Output: ../meshes/pipe_hollow.stl  (binary STL)

Usage:
    python3 generate_pipe_mesh.py
"""

import os
import struct

import numpy as np

# ------------------------------------------------------------------ #
# Parameters
# ------------------------------------------------------------------ #
INNER_RADIUS    = 0.15    # metres - matches default pipe_radius in pipe_perception
WALL_THICKNESS  = 0.03    # metres
OUTER_RADIUS    = INNER_RADIUS + WALL_THICKNESS   # 0.18 m
PIPE_LENGTH     = 5.0     # metres along Z axis
N_SEGMENTS      = 64      # circumference resolution (higher = smoother)

OUTPUT_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "meshes", "pipe_hollow.stl",
)


# ------------------------------------------------------------------ #
# Helpers
# ------------------------------------------------------------------ #

def _normal(v0, v1, v2):
    """Unit normal of triangle v0-v1-v2 via cross product."""
    v0, v1, v2 = np.array(v0), np.array(v1), np.array(v2)
    e1 = v1 - v0
    e2 = v2 - v0
    n  = np.cross(e1, e2)
    mag = np.linalg.norm(n)
    return (n / mag).tolist() if mag > 1e-12 else [0.0, 0.0, 1.0]


def _add_tri(triangles, v0, v1, v2):
    triangles.append((_normal(v0, v1, v2), v0, v1, v2))


def _add_quad(triangles, v00, v01, v10, v11):
    """
    Quad split into two triangles:
      v00--v10
       |  / |
      v01--v11
    Winding: CCW when viewed from the normal side.
    """
    _add_tri(triangles, v00, v10, v01)
    _add_tri(triangles, v10, v11, v01)


# ------------------------------------------------------------------ #
# Mesh generation
# ------------------------------------------------------------------ #

def build_hollow_cylinder(inner_r, outer_r, length, n_segs):
    """Return list of (normal, v0, v1, v2) tuples."""
    triangles = []

    angles = np.linspace(0.0, 2.0 * np.pi, n_segs, endpoint=False)

    for i in range(n_segs):
        j   = (i + 1) % n_segs
        ai  = angles[i]
        aj  = angles[j]

        # Trig values
        ci, si = np.cos(ai), np.sin(ai)
        cj, sj = np.cos(aj), np.sin(aj)

        # Eight corner vertices for this quad strip
        oi0 = (outer_r * ci, outer_r * si, 0.0)
        oi1 = (outer_r * ci, outer_r * si, length)
        oj0 = (outer_r * cj, outer_r * sj, 0.0)
        oj1 = (outer_r * cj, outer_r * sj, length)

        ii0 = (inner_r * ci, inner_r * si, 0.0)
        ii1 = (inner_r * ci, inner_r * si, length)
        ij0 = (inner_r * cj, inner_r * sj, 0.0)
        ij1 = (inner_r * cj, inner_r * sj, length)

        # 1. Outer surface — CCW from outside → outward normals
        _add_quad(triangles, oi0, oi1, oj0, oj1)

        # 2. Inner surface — CW from outside = CCW from inside → inward normals
        #    Swap i and j to reverse winding.
        _add_quad(triangles, ij0, ij1, ii0, ii1)

        # 3. End cap at Z=0 — normal points -Z
        #    Winding: CCW when viewed from -Z side (i.e. CW from +Z)
        _add_tri(triangles, oi0, oj0, ij0)
        _add_tri(triangles, oi0, ij0, ii0)

        # 4. End cap at Z=length — normal points +Z
        _add_tri(triangles, oi1, ij1, oj1)
        _add_tri(triangles, oi1, ii1, ij1)

    return triangles


# ------------------------------------------------------------------ #
# Binary STL writer
# ------------------------------------------------------------------ #

def write_binary_stl(triangles, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)

    header = b"Hollow pipe mesh generated by generate_pipe_mesh.py"
    # STL header must be exactly 80 bytes
    header = header[:80].ljust(80, b" ")

    with open(path, "wb") as f:
        f.write(header)
        f.write(struct.pack("<I", len(triangles)))
        for normal, v0, v1, v2 in triangles:
            f.write(struct.pack("<3f", *normal))
            f.write(struct.pack("<3f", *v0))
            f.write(struct.pack("<3f", *v1))
            f.write(struct.pack("<3f", *v2))
            f.write(struct.pack("<H", 0))   # attribute byte count


# ------------------------------------------------------------------ #
# Entry point
# ------------------------------------------------------------------ #

def main():
    print("Generating hollow cylinder mesh...")
    print(f"  Inner radius : {INNER_RADIUS} m")
    print(f"  Outer radius : {OUTER_RADIUS} m")
    print(f"  Length       : {PIPE_LENGTH} m")
    print(f"  Segments     : {N_SEGMENTS}")

    tris = build_hollow_cylinder(INNER_RADIUS, OUTER_RADIUS, PIPE_LENGTH, N_SEGMENTS)

    out = os.path.abspath(OUTPUT_PATH)
    write_binary_stl(tris, out)

    size_kb = os.path.getsize(out) / 1024
    print(f"Done: {len(tris)} triangles written to {out}  ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()